# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

#想修改名字直接改这里
title: The Journey of Xingyu ZHU #站点的名称
email: funny_wade@outlook.com
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to my extraordinary journey captured in camera! 
  Embark on an immersive adventure through captivating landscapes, vibrant cultures, and unforgettable moments frozen in time. 
  Join me as I traverse the globe, sharing tales of exploration and discovery through the lens of my camera. 
  From the serene shores of secluded beaches to the bustling streets of bustling cities, each photograph tells a story, inviting you to wanderlust alongside me. 
  Whether you seek inspiration for your next escapade or simply crave a visual escape, let my site be your passport to wanderlust and wonder.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://xingyujourney.github.io" # the base hostname & protocol for your site, e.g. http://example.com
#上面的url后面不应该加/，因为navigation的前面加了/
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
theme: minimal-mistakes-jekyll

# Build settings
markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag

# Customize your site
author:
  name: XingyuZHU
  avatar: "/assets/avatar/spike.jpg"
  bio: "A Computer Science Student"
  location: "UK"
  email: "funny_wade@outlook.com"
  links:
    - label: "GitHub"
      url: "https://xingyujourney.github.io/"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
